### ISSUE TITLE
Checkpoint 1 is ready for review

### ISSUE THREAD

**Issue by palmerlarson** [palmerlarson/IndieProject#2]
@pawaitemadisoncollege - checkpoint 1 is ready for review

**Comment by pawaitemadisoncollege** [comment]
Problem statement and solution on readme.md are well-defined. Good explanation of what makes this project unique. 

- [x] Glad to see you are using Trello - such a great tool! I just sent a request for access since the board is private. Can you give my account (pawaite@gmail.com) view access?
- [x] Are all user stories MVP? It may be a good idea to limit the scope of what you are committing to - be sure to leave stories that cover CRUD, sign-up, and sign-in so that you hit the ent java indie project objectives.  I think good v.next might be the social aspect. 
- [x] Thoughts on making the user stories more granular? If the story states, "the user would also like... " should that be another story?
- [x] Screen designs show you've thought carefully about much of the functionality. I think it would be helpful to add in the fields for any page that has a submit button. For example, what must the user type in to add an asset? This will help inform the database design. 
- [x] Are all user stories represented in the screen designs and vice versa? For example, there are pdf export buttons on the screens, but I am not sure which stories indicate an export option. 
- [x] Are you planning to use JFreeChart for pdf creation? It seems this could meet the java api requirement for class. 
- [x] I am not sure how great JFreeChart is for producing charts for the web. A javascript option (there are many) might produce a better result, and this would add to the level of complexity and independent learning (see rubric). Keep it in mind if JFreeChart doesn't produce the look you want.
- [x] https://github.com/palmerlarson/IndieProject/blob/master/timeLog.md - formatting would be improved - the markdown hashes are showing up. I think it may just need a space between the `#` and the text.
- [x] Time log should include all time spent on this class in addition to the indie project. 

Really looking forward to seeing progress in the next few weeks on this @palmerlarson. Cool project!

**Comment by palmerlarson** [comment]
Hi Paula,
I apologize I forgot to respond to this.

Thanks for all of this! I updated my user stories to show the MVP stories. You have gave me a lot to think about with this project. I'm going to implement changes to the screen design as well as update the timelog when I'm working on all class materials. I'm hoping to knock out most of the high-level design and get working on the program itself this weekend. Let me know if you think I'm missing anything or if you think I'm biting off more than I can chew.

Thanks again!

**Comment by pawaitemadisoncollege** [comment]
Hi @palmerlarson - Looking at the mvp, I think this is sized pretty well!

- [x] You'll see in week 7 that AWS Cognito will take care of the password reset business for you, so that one can be mvp as well. 
- [x] I like that you are laying out tasks in Trello. This could be improved by laying out the tasks needed to complete each user story.  Adding the tasks to meet checkpoint 2 and 3 may be helpful as well.  
- [x] I highly recommend adding target dates for each task. I think Trello lets you sort/filter by date so this may help keep things organized and help more easily prioritize your work.

**Comment by pawaitemadisoncollege** [comment]
Just noticed one more thing 

- [x] Missing a .gitignore file (or did I overlook this?)

**Comment by palmerlarson** [comment]
Hey! @pawaitemadisoncollege 
Looks like my .gitignore file ended up in the src folder somehow. I moved it back to the main directory. Sorry about that!

I added some goal dates on my Trello board, thanks for that idea!
Can't wait to learn how AWS Cognito works!

**Comment by pawaitemadisoncollege** [comment]
Glad to hear the feedback is helpful @palmerlarson. You are the only one using Trello this semester - I think I'm going to encourage that for future semesters - way better than that text version plan I used.  

Have a great rest of the week!
